---
version: 2
updates:
  # ---------------------------------------------------------------------------
  # GitHub Actions
  # ---------------------------------------------------------------------------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"

  # ---------------------------------------------------------------------------
  # NPM
  # ---------------------------------------------------------------------------
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
