# -----------------------------------------------------------------------------
# This GitHub Actions workflow ensures pull requests contain commits following
# the Conventional Commits format. It uses this information to label the pull
# requests accordingly.
#
# Notable File history (see commits in each repository for details):
#   - 2022-06-06: Created for https://github.com/olivr/template-repo
#
# Copyright 2022 Romain Barissat. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
# -----------------------------------------------------------------------------
---
name: conventional-commits

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [synchronize, opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commits against Conventional Commits format
        uses: aevea/commitsar@v0.20.0

      - name: Add labels according to the Conventional Commits
        uses: bcoe/conventional-release-labels@v1
