# --------------------------------------------------------
# This workflow comments on each new issue with a message
# explaining how to vote on the issue.
# --------------------------------------------------------
---
name: issue-voting

permissions:
  issues: write

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    name: Auto-comment
    if: github.event.issue.title != 'Dependency Dashboard'
    steps:
      - name: Generate app token
        id: generate_token
        # yamllint disable-line rule:line-length
        uses: peter-murray/workflow-application-token-action@e8782d687a306fb13d733244d0f2a50e272d3752
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permissions: issues:write
          # Uncomment if the app is installed at the organization level
          # organization: ${{ github.repository_owner }}

      - name: Add voting reactions to issue
        uses: aidan-mundy/react-to-issue@b189f43a4686d4183c80c957dbcec07a720be261
        with:
          issue-number: ${{github.event.issue.number}}
          reactions: +1, -1
          token: ${{ steps.generate_token.outputs.token }}

      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@b95e16d2859ad843a14218d1028da5b2c4cbc4b4
        with:
          issue-number: ${{github.event.issue.number}}
          body: >
            ## Do's


            - Please **do** use the 👍 and 👎 reactions to show your interest.

            - Please **do** add constructive comments to help the community.

            - Please **do** consider contributing with a pull request to resolve this issue.


            ## Don'ts


            - Please **do not** comment on this issue for the sole purpose of **bumping, asking for
            a fix, showing your interest, +1, etc.**


            ## Notifications


            - To be notified when activity occurs **on this issue**, click "**Subscribe**" on the
            right hand side of this page.

            - To be notified when activity occurs **on this repo**, give it a ⭐️ and choose your
            notification preferences under "**Watch**" at the top.
          reactions: eyes
          token: ${{ steps.generate_token.outputs.token }}

      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@b95e16d2859ad843a14218d1028da5b2c4cbc4b4
        with:
          issue-number: ${{github.event.issue.number}}
          body: >
            Thank you @${{ github.event.issue.user.login }} for opening an issue, a maintainer will
            look at it shortly.
          token: ${{ steps.generate_token.outputs.token }}
