# --------------------------------------------------------
# This workflow will lint each PR and commit.
# rebase their PR by commenting '/rebase' on their PR.
# --------------------------------------------------------
---
name: lint

permissions:
  statuses: write

on:
  pull_request_target:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Super Linter
        # https://github.com/github/super-linter#slim-image
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YAML_CONFIG_FILE: ../../../github/workspace/.yamllint.yaml
          # Validate only new/changed files unless this workflow is triggered manually
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          # Do not run Gitleaks because we are already using TruffleHog
          VALIDATE_GITLEAKS: false
          FILTER_REGEX_EXCLUDE: (LICENSE|CHANGELOG).md
