# --------------------------------------------------------
# This workflow allows users of this repo to automatically
# rebase their PR by commenting '/rebase' on their PR.
# --------------------------------------------------------
---
name: rebase

permissions:
  contents: write
  pull-requests: read

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    runs-on: ubuntu-latest
    name: Automatic Rebase
    if: >-
      github.event.issue.pull_request != '' && 
      (
        contains(github.event.comment.body, '/rebase') || 
        contains(github.event.comment.body, '/autosquash')
      )

    steps:
      - name: Generate app token
        id: generate_token
        # yamllint disable-line rule:line-length
        uses: peter-murray/workflow-application-token-action@e8782d687a306fb13d733244d0f2a50e272d3752
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permissions: contents:write, pull_requests:read
          # Uncomment if the app is installed at the organization level
          # organization: ${{ github.repository_owner }}

      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@418e518867c393c55df77cb1a4c4001982db51aa
        with:
          autosquash: >
            ${{ 
              contains(github.event.comment.body, '/autosquash') ||
              contains(github.event.comment.body, '/rebase-autosquash')
            }}
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
